Class cysnet.clinicaDental.agenda.msg.BuscarAltaPacientePorCitaRequest Extends Ens.Request
{

Property idCita As %Integer;

Storage Default
{
<Data name="BuscarAltaPacientePorCitaRequestDefaultData">
<Subscript>"BuscarAltaPacientePorCitaRequest"</Subscript>
<Value name="1">
<Value>idCita</Value>
</Value>
</Data>
<DefaultData>BuscarAltaPacientePorCitaRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
