Class cysnet.clinicaDental.agenda.msg.BuscarAdmisionPorCitaRequest Extends Ens.Request
{

Property idCita As %Integer;

Storage Default
{
<Data name="BuscarAdmisionPorCitaRequestDefaultData">
<Subscript>"BuscarAdmisionPorCitaRequest"</Subscript>
<Value name="1">
<Value>idCita</Value>
</Value>
</Data>
<DefaultData>BuscarAdmisionPorCitaRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
